config/routes.rb
Rails.application.routes.draw do
  resources :letters
  get 'user/show_letters', to: 'letters#index', as: 'show_letters'
  resources :posts
  get 'feed_posts', to: 'posts#index', as: 'feed_posts'
  devise_for :users, :path => 'accounts', controllers: { registrations: "registrations", :omniauth_callbacks => "callbacks" }
  resources :users
  patch 'update_avatar/:id', to: 'users#update_avatar', as: 'update_avatar'
  resources :friendships
  delete 'destroy_friendship/:id', to: 'friendships#destroy_friendship', as: 'destroy_friendship'
  resources :comments
  resources :likes
  root 'home#index'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  has_many :friendships, foreign_key: "friend_invite_id", class_name: "Friendship"
  has_many :invited_friend, through: :friendships, source: :invited_friend 
  has_many :invites_friend, class_name: "Friendship", foreign_key: "invited_friend_id"
  has_many :friends, through: :invites_friend, source: :friend_invite 
  has_many :posts
  has_many :comments
  has_many :likes
  has_one_attached :avatar

  # after_create :welcome_mail
  


  def invitations?
    invites_friend.not_accepted.count > 0
  end

  def number_invitations
    invites_friend.not_accepted.count
  end

  def get_friendship_id(user)
    if self.friendships.has_invited(user).count == 1
      friendships.has_invited(user).ids
    elsif self.invites_friend.has_invitation(user).count == 1
      invites_friend.has_invitation(user).ids
    end
  end

  def has_invited?(user)
    friendships.has_invited(user).count == 1
  end

  

  def invitation?(user)
    if self.invites_friend.has_invitation(user).not_accepted.count == 1
      return true
    elsif self.friendships.has_invited(user).not_accepted.count == 1
      return true
    else 
      return false
    end
  end

  def friendship?(user)
    if self.invites_friend.has_invitation(user).accepted.count == 1
      return true
    elsif self.friendships.has_invited(user).accepted.count == 1
      return true
    else 
      return false
    end
  end

  def friends
    ids = []
    user_has_invitation = self.invites_friend.accepted.each {| friend |   ids.push(friend.friend_invite_id) } 
    user_has_invitated = self.friendships.accepted.each {| friend |   ids.push(friend.invited_friend_id) } 
      return ids
  end


  def get_posts
    friends = self.friends.join(", ")
    if self.friends.count > 0
      Post.timeline_friends(friends, self.id)
    else
      Post.timeline_only(self.id)
    end
  end


  def number_friends
    total_friends = 0
    number = self.invites_friend.accepted.count + self.friendships.accepted.count
    total_friends+=number 
  end
  



  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end


  def welcome_mail
    UserMailer::welcome_email(self).deliver
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def index
        @users = User.all
        @friendship = Friendship.new
    end


    def show
        @user = User.find(params[:id])
        @num_friends = @user.number_friends
        @friendship = Friendship.new
        @feed = Post.order(created_at: :desc).where(user_id: params[:id])
        @comment = Comment.new
        @like = Like.new
        @letter = Letter.new
    end

    def update_avatar
        @user = User.find(params[:id])
        @user.avatar.attach(params[:user][:avatar])
        if @user.avatar.attached?
            redirect_to root_path
        else
            redirect_to @user
        end
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
    def user_gravatar(user, size)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name)
    end
end

app/views/users/_change_avatar.html.erb
<div class="modal-avatar">
     <%# Modal %>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
      Change Avatar
    </button>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Changer your avatar</h4>
          </div>
          <div class="modal-body">
            <%= form_for(@user, url: update_avatar_path(@user.id)) do |form| %>
              <%= form.file_field :avatar %>
              <%= form.submit "Update Avatar", class: 'btn btn-primary space'%>
            <% end %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/users/_send_message.html.erb
<div class="modal-avatar">
     <%# Modal %>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
      Send Letter
    </button>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Send a Letter</h4>
          </div>
          <div class="modal-body">
            <%= form_for(@letter, url: letters_path ) do |form| %>
              <%= form.hidden_field :receiver_id, value: @user.id %>
              <%= form.text_area :message, class: 'form-control', placeholder: "Please write your letter" %>
              <%= form.submit "Send Letter", class: 'btn btn-primary space'%>
            <% end %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="control">
<% @users.each do |user| %>
  <% if user != current_user %>
    <div class="media col-md-4">
      <div class="media-left media-middle">
        <a href="users/<%= user.id %>">
          <% if user.avatar.attached? %>
            <%= image_tag(user.avatar, size: 75) %>
          <% else %>
            <%= user_gravatar(user, 75) %>
          <% end %>
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= link_to user.name, user_path(user.id)  %></h4> 
        <span class="add-<%= user.id %>">
          <%= render "shared/friend_control", user: user %>
        </span>
      </div>
    </div>

  <% end %>
    
<% end %>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-3">
    <div class="media">
      <div class="media-left media-middle">
        <a href="<%= user_path(@user.id) %>">
          <% if @user.avatar.attached? %>
            <%= image_tag(@user.avatar, size: 105) %>
          <% else %>
            <%= user_gravatar(@user, 105) %>
          <% end %>
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= @user.name %></h4>
        <%= render "shared/friend_control", user: @user %>
        <p></p>
        <span style="margin-top:5px">
          <a href="#" class="btn btn-success">
            Friends <span class="badge"><%= @num_friends %></span>
          </a>
        </span>
      </div>
    </div>
    <% if current_user == @user %>
      <%= render 'change_avatar' %>
    <% end %>
  </div>
  <div class="col-sm-6">
    <% if current_user.friendship?(@user) || current_user == @user %>
      <% @feed.each do |feed| %>
        <% if feed.user.avatar.attached? %>
          <h4><%= image_tag(feed.user.avatar, size: 45) %> <%= feed.user.name %></h4>
        <% else %>
          <h4><%= user_gravatar(feed.user, 45) %> <%= feed.user.name %></h4>
        <% end %>
        <h5 class="title"><%= feed.title %></h5>
        <p class="feed_content"><%= feed.content %></p>
        <% if feed.photo.attached? %>
          <img src="<%= url_for(feed.photo) %>"  class="img-responsive">
        <% end %>
        <%= render "shared/likes", post: feed %>
        <hr>
        <h5>Comments</h5>
      <div class="comments-<%= feed.id %>">
        <% feed.comments.each do |comment| %>
          <%= render "shared/comments", comment: comment %>
        <% end %>
      </div>
          <%= render 'shared/comment_form', id: feed.id %>
        <hr>
      <% end %>
    <% else %>
      <h4 class="text-center"> <b><%= @user.name %></b> is not your friend <span class="glyphicon glyphicon-ban-circle red-color" aria-hidden="true"></span> </h4>
    <% end %>
  </div>
  <div class="col-sm-3"></div>
</div>