config/routes.rb
Rails.application.routes.draw do
  resources :letters
  get 'user/show_letters', to: 'letters#index', as: 'show_letters'
  resources :posts
  get 'feed_posts', to: 'posts#index', as: 'feed_posts'
  devise_for :users, :path => 'accounts', controllers: { registrations: "registrations", :omniauth_callbacks => "callbacks" }
  resources :users
  patch 'update_avatar/:id', to: 'users#update_avatar', as: 'update_avatar'
  resources :friendships
  delete 'destroy_friendship/:id', to: 'friendships#destroy_friendship', as: 'destroy_friendship'
  resources :comments
  resources :likes
  root 'home#index'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

end

app/views/shared/_comment_form.html.erb
<%= form_with(model: @comment, url: comments_path, remote: true ) do |f| %>
  <%= f.hidden_field :post_id, value: id %>
  <%= f.text_area :body, class: "form-group col-sm-12 btn-comment form-#{id}", rows: "1" %><br>
  <%= f.submit "Comment", :onclick => "", data: { "disable-with": "Saving..." }, class: "btn btn-primary" %>
<% end %>

app/views/shared/_comments.html.erb
<div class="media">
  <div class="media-left media-middle">
    <a href="#">
      <% if comment.user.avatar.attached? %>
        <%= image_tag(comment.user.avatar, size: 45) %>
      <% else %>
        <%= user_gravatar(comment.user, 35) %>
      <% end %>
    </a>
  </div>
  <div class="media-body">
    <p class="feed_comment"><span class="comment_name"><%= comment.user.name %></span> <%= comment.body %></p>
  </div>
</div>

app/views/shared/_friend_control.html.erb
<span class="add-<%= user.id %>">
    <% if user != current_user %>
        <% if current_user.friendship?(user) %>
    <%= link_to "Cancel Friendship", destroy_friendship_path(current_user.get_friendship_id(user)), remote: true, method: :delete, class: "btn btn-danger" %>
    <% elsif current_user.invitation?(user) %>
    <% if current_user.has_invited?(user) %>
    <%= link_to "Cancel Invitation", friendship_path(current_user.get_friendship_id(user)), remote: true, method: :delete, class: "btn btn-danger" %>
    <% else %>
    <%= link_to "Accept Invitation", friendship_path(current_user.get_friendship_id(user)), remote: true, method: :patch, class: "btn btn-success" %>
    <% end %>
    <% else %>
    <%= link_to "Request Friendship", friendships_path(friendship:  {invited_friend_id: user.id } ), remote: true, method: :post, class: "btn btn-primary" %>
    <% end %> 
    <% end %>
</span>

app/views/shared/_likes.html.erb
 <div class="likes-<%= post.id %>">
                     <% if post.like?(current_user) %>
                    <p style="color: green">
                         <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true">
                              Already like | <%= post.total_likes %>
                         </span>
                    </p>
               <% else %>
                    <%= form_with(model: @like, url: likes_path(like:  {post_id: post.id } ), remote: true ) do |f| %>
                         <%= button_tag(type: "submit", class: "btn btn-primary") do %>
                              <span><i class="glyphicon glyphicon-thumbs-up"></i> Like</span>
                         <% end %>
                    <% end %>
               <% end %>
</div>