config/routes.rb
Rails.application.routes.draw do
  resources :letters
  get 'user/show_letters', to: 'letters#index', as: 'show_letters'
  resources :posts
  get 'feed_posts', to: 'posts#index', as: 'feed_posts'
  devise_for :users, :path => 'accounts', controllers: { registrations: "registrations", :omniauth_callbacks => "callbacks" }
  resources :users
  patch 'update_avatar/:id', to: 'users#update_avatar', as: 'update_avatar'
  resources :friendships
  delete 'destroy_friendship/:id', to: 'friendships#destroy_friendship', as: 'destroy_friendship'
  resources :comments
  resources :likes
  root 'home#index'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

end

app/models/post.rb
class Post < ApplicationRecord 
  belongs_to :user
  has_many :comments
  has_many :likes
  has_one_attached :photo

  validates :title, presence: true
  validates :content, presence: true


  def like?(user)
    likes.where(user_id: user.id).count > 0
  end

  def total_likes
    likes.count
  end


  def self.timeline_friends(list_friends, id)
    where("user_id IN (#{list_friends}) OR user_id = #{id}").order(created_at: :desc)
  end

  def self.timeline_only(id)
    where("user_id = #{id}").order(created_at: :desc)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index]

  # GET /posts
  # GET /posts.json
  def index
    @feed_posts = current_user.get_posts
    @comment = Comment.new
    @like = Like.new
    @user = User.find(current_user.id)        
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

      if @post.save
        flash[:success] = "Post was successfully created."
         redirect_to feed_posts_path
      else
        render :new 
      end

  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :photo)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
    <% @feed_posts.each do |post| %>
      <% if post.user.avatar.attached? %>
         <h4><%= image_tag(post.user.avatar, size: 45) %> <%= link_to post.user.name, user_path(post.user.id) %></h4>
      <% else %>
        <h4><%= user_gravatar(post.user, 45) %> <%= link_to post.user.name, user_path(post.user.id) %></h4>
      <% end %>
      <h5 class="title"><%= post.title %></h5>
      <p class="feed_content"><%= post.content %></p>
      <% if post.photo.attached? %>
        <img src="<%=(url_for(post.photo))%>" class="img-responsive" >
      <% end %>
      <hr>
      <%= render "shared/likes", post: post %>
      <h5>Comments</h5>
      <div class="comments-<%= post.id %>">
        <% post.comments.each do |comment| %>
          <%= render "shared/comments", comment: comment %>
        <% end %>
      </div>
      <%= render 'shared/comment_form', id: post.id %>
      <hr>
    <% end %>
  </div>
  <div class="col-sm-3"></div>
</div>

app/views/posts/new.html.erb
<div class="row">
    <div class="col-sm-3"></div> 
    <div class="col-sm-6">
      <h1>New Post</h1>

        <%= form_with(model: @post, local: true) do |form| %>
          <% if @post.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

              <ul>
              <% @post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div>
            <%= form.label :title %>
            <%= form.text_field :title, class: "form-control" %>
          </div><br>

          <div>
            <%= form.label :content %>
            <%= form.text_area :content, class: "form-control" %>
          </div><br>

          <div>
            <%= form.label :content %>
            <%= form.file_field :photo, class: "form-control" %>
          </div><br>

          <div class="actions">
            <%= form.submit "Post", class: "btn btn-primary" %>
            <%= link_to 'Back', "/feed", class: "btn btn-warning" %>
          </div>
        <% end %>
    </div>
    <div class="col-sm-3"></div> 
</div>



      

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>