config/routes.rb
Rails.application.routes.draw do
  resources :letters
  get 'user/show_letters', to: 'letters#index', as: 'show_letters'
  resources :posts
  get 'feed_posts', to: 'posts#index', as: 'feed_posts'
  devise_for :users, :path => 'accounts', controllers: { registrations: "registrations", :omniauth_callbacks => "callbacks" }
  resources :users
  patch 'update_avatar/:id', to: 'users#update_avatar', as: 'update_avatar'
  resources :friendships
  delete 'destroy_friendship/:id', to: 'friendships#destroy_friendship', as: 'destroy_friendship'
  resources :comments
  resources :likes
  root 'home#index'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Livebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top" style="background: #4267b2; color:#fff">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/" style="color:#fff"><b>Livebook</b></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          
          <ul class="nav navbar-nav navbar-right" style="margin-top:0.8%; color:#fff">
            <% if user_signed_in? %>
              <li><%= link_to raw("<span><i class='glyphicon glyphicon-edit'></i> New Post</span>"), new_post_path %></li>
              <% if current_user.invitations? %>
              <li><%= link_to raw("<span>Friends <i class='glyphicon glyphicon-plus-sign red-color'>#{current_user.number_invitations}</i></span>"), users_path %></li>
              <% else %>
              <li><%= link_to "Friends", users_path %></li>
              <% end %>
              

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span><i class='glyphicon glyphicon-user'></i></span> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="/users/<%= current_user.id %>">Profile</a></li>
                  <li><%= link_to "Settings", edit_user_registration_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to raw("<span><i class='glyphicon glyphicon-off'></i> Sign out</span>"), destroy_user_session_path, :method => :delete%></li>
                </ul>
              </li>
              
            <% else %>
              <%= form_for(resource, as: resource_name, url: session_path(resource_name), :html => {class: "form-inline"} ) do |f| %>
    
                  <%= f.label :email %>
                  <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", id: "login_email" %>
                

                
                  <%= f.label :password %>
                  <%= f.password_field :password, autocomplete: "current-password", class: "form-control", id: "login_password" %>
                

                <% if devise_mapping.rememberable? %>
                  
                    <%= f.check_box :remember_me %>
                    <%= f.label :remember_me %>
                  
                <% end %>

                
                  <%= f.submit "Log in", class: "btn btn-success" %>
                  <%= render "devise/shared/links" %>
              <% end %>
              <span style="margin-left: 37%"><%= link_to "Forgot your password?", new_password_path(resource_name) %></span>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container control">
      <div style="margin-top:90px"> 
        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      </div>
      <% if user_signed_in? == false %>
        <div class="pull-right">
          <h3>Register</h3><hr>
          <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <%= render "devise/shared/error_messages", resource: resource %>

            <div class="field">
              <%= f.label :email %><br />
              <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
            </div>

            <div class="field">
              <%= f.label :name %><br />
              <%= f.text_field :name, autocomplete: "name", class: "form-control" %>
            </div>

            <div class="field">
              <%= f.label :password %>
              <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br />
              <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
            </div>

            <div class="field">
              <%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
            </div><br>

            
              <%= f.submit "Sign up", class: "btn btn-success" %>
            
          <% end %>
          <br>
          
        </div>
      <% end %>
    <%= yield %>
    </div>
  </body>
</html>